sudo: required
services:
        - docker

before_install:
        - docker build -t vikashkumar/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true vikashkumar/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: "vikash-react"
        env: "VikashReact-env"
        bucket_name: "arn:aws:s3:::elasticbeanstalk-ap-south-1-007131111482"
        bucket_path: "vikash-react"
        on:
           branch: master
        access_key_id:
                secure: "$AWS_ACCESS_KEY"
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
